### ISSUE TITLE
Breaking changes in 0.2.7 -> 0.2.10

### ISSUE THREAD

**Issue by acheroncrypto** [Fairglow/index-list#5]
After the recent [`0.2.10`](https://crates.io/crates/index_list/0.2.10) release, some of the crates that depend on `index_list` broke because of the breaking changes in https://github.com/Fairglow/index-list/commit/28d11eab75b705f54b11ab4fe392a238289a0f70

```
   Compiling solana-accounts-db v1.17.4
error[E0432]: unresolved import `index_list::Index`
 --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/solana-accounts-db-1.17.4/src/read_only_accounts_cache.rs:5:18
  |
5 |     index_list::{Index, IndexList},
  |                  ^^^^^ no `Index` in the root
  |
  = help: consider importing one of these items instead:
          std::ops::Index
          core::ops::Index

For more information about this error, try `rustc --explain E0432`.
error: could not compile `solana-accounts-db` (lib) due to previous error
```

Would you consider yanking the last release and re-releasing it as `0.3.0`?

**Comment by Fairglow** [comment]
How about I release ` 0.2.11` with a type alias for `Index`  on the root level? I.e. in `lib.rs` :
```rust
pub type Index = ListIndex;
```

Wouldn't that satisfy your need?

**Comment by Fairglow** [comment]
See [commit 0d4246f](https://github.com/Fairglow/index-list/commit/0d4246ffc18846f03d9be3fbb587397a44a87e9b)

**Comment by acheroncrypto** [comment]
> How about I release `0.2.11` with a type alias for `Index` on the root level? I.e. in `lib.rs` :
> 
> ```rust
> pub type Index = ListIndex;
> ```
> 
> Wouldn't that satisfy your need?

Thanks, that should also solve this error but I haven't verified if the missing `Index` type is the only incompatibility issue between the releases.

**Comment by Fairglow** [comment]
I've published `0.2.11` with this fix. Let me know if there is anything else... Or if this is enough

**Comment by acheroncrypto** [comment]
It works now, thank you!
